force-app/main/default/objects/Round_Robin__c/Round_Robin__c.object-meta.xml
<CustomObject>
    <label>Round Robin</label>
    <nameField>
        <label>Round Robin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Round Robins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Round_Robin__c/fields/Assign_Field__c.field-meta.xml
<CustomField>
    <fullName>Assign_Field__c</fullName>
    <label>Assign Field</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Round_Robin_Member__c/Round_Robin_Member__c.object-meta.xml
<CustomObject>
    <label>Round Robin Member</label>
    <nameField>
        <displayFormat>RRM # {0000}</displayFormat>
        <label>Round Robin Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Round Robin Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Round_Robin_Member__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Round Robin Members</relationshipLabel>
    <relationshipName>Round_Robin_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Round_Robin_Member__c/fields/Last_Assigned__c.field-meta.xml
<CustomField>
    <fullName>Last_Assigned__c</fullName>
    <label>Last Assigned</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Round_Robin_Member__c/fields/Round_Robin__c.field-meta.xml
<CustomField>
    <fullName>Round_Robin__c</fullName>
    <label>Round Robin</label>
    <referenceTo>Round_Robin__c</referenceTo>
    <relationshipLabel>Round Robin Members</relationshipLabel>
    <relationshipName>Round_Robin_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RoundRobin.cls
public class RoundRobin {

    public static void initialize(List<sObject> newRecords, List<sObject> oldRecords) {
        String objectName = newRecords[0].getSObjectType().getDescribe().getName();
        List<Round_Robin_Member__c> members = RoundRobinService.getMembers(objectName);
        String assignField = members[0].Round_Robin__r.Assign_Field__c;
        Integer membersSize = members.size();
        Integer index = 0;
        DateTime dt = DateTime.Now();
        Long longtime = dt.getTime();
        for(sObject record : newRecords){
            if(index == membersSize) index = 0;
            record.put(assignField, members[index].Contact__c);
            members[index].Last_Assigned__c = DateTime.newInstance(longtime);
            index++;
            longtime++;
        }

        update members;
    }

}