force-app/main/default/objects/Round_Robin__c/Round_Robin__c.object-meta.xml
<CustomObject>
    <label>Round Robin</label>
    <nameField>
        <label>Round Robin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Round Robins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Round_Robin__c/fields/Assign_Field__c.field-meta.xml
<CustomField>
    <fullName>Assign_Field__c</fullName>
    <label>Assign Field</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Round_Robin__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>API Name of Object</description>
    <label>Object</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Round_Robin_Member__c/Round_Robin_Member__c.object-meta.xml
<CustomObject>
    <label>Round Robin Member</label>
    <nameField>
        <displayFormat>RRM # {0000}</displayFormat>
        <label>Round Robin Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Round Robin Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Round_Robin_Member__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Round Robin Members</relationshipLabel>
    <relationshipName>Round_Robin_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Round_Robin_Member__c/fields/Last_Assigned__c.field-meta.xml
<CustomField>
    <fullName>Last_Assigned__c</fullName>
    <label>Last Assigned</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Round_Robin_Member__c/fields/Last_Assigned_Epoch__c.field-meta.xml
<CustomField>
    <fullName>Last_Assigned_Epoch__c</fullName>
    <description>The Last_Assigned__c date as an integer.</description>
    <label>Last Assigned (Epoch)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Round_Robin_Member__c/fields/Round_Robin__c.field-meta.xml
<CustomField>
    <fullName>Round_Robin__c</fullName>
    <label>Round Robin</label>
    <referenceTo>Round_Robin__c</referenceTo>
    <relationshipLabel>Round Robin Members</relationshipLabel>
    <relationshipName>Round_Robin_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RoundRobinService.cls
public class RoundRobinService {

    public static List<Round_Robin_Member__c> getMembers(String objectName) {
        List<Round_Robin_Member__c> members = [select Id, Contact__c, Last_Assigned__c,Last_Assigned_Epoch__c, Round_Robin__r.Assign_Field__c from Round_Robin_Member__c where Active__c = true and Round_Robin__r.Object__c = :objectName order by Last_Assigned_Epoch__c asc];
        return members;
    }

}